from collections.abc import Iterator
from collections.abc import Sequence

import numpy as np

class NullPointerException(Exception): ...

class OcTreeKey:
    def __init__(self) -> None: ...
    def __setitem__(self, key: int, value: int) -> None: ...
    def __getitem__(self, key: int) -> int: ...
    def __eq__(self, other: object) -> bool: ...
    __hash__: None

class OcTreeNode:
    def addValue(self, p: float) -> None: ...
    def childExists(self, i: int) -> bool: ...
    def getValue(self) -> float: ...
    def setValue(self, v: float) -> None: ...
    def getOccupancy(self) -> float: ...
    def getLogOdds(self) -> float: ...
    def setLogOdds(self, l: float) -> None: ...
    def hasChildren(self) -> bool: ...

class iterator_base:
    def getCoordinate(self) -> np.ndarray: ...
    def getDepth(self) -> int: ...
    def getKey(self) -> OcTreeKey: ...
    def getIndexKey(self) -> OcTreeKey: ...
    def getSize(self) -> float: ...
    def getX(self) -> float: ...
    def getY(self) -> float: ...
    def getZ(self) -> float: ...
    def getOccupancy(self) -> float: ...
    def getValue(self) -> float: ...

class tree_iterator(iterator_base):
    def next(self) -> tree_iterator: ...
    def __iter__(self) -> Iterator[tree_iterator]: ...
    def isLeaf(self) -> bool: ...

class leaf_iterator(iterator_base):
    def next(self) -> leaf_iterator: ...
    def __iter__(self) -> Iterator[leaf_iterator]: ...

class leaf_bbx_iterator(iterator_base):
    def next(self) -> leaf_bbx_iterator: ...
    def __iter__(self) -> Iterator[leaf_bbx_iterator]: ...

class OcTree:
    def __init__(self, arg: float | str | bytes) -> None: ...
    @staticmethod
    def read(filename: str | bytes) -> OcTree: ...
    def adjustKeyAtDepth(self, key: OcTreeKey, depth: int) -> OcTreeKey: ...
    def bbxSet(self) -> bool: ...
    def calcNumNodes(self) -> int: ...
    def clear(self) -> None: ...
    def coordToKey(
        self, coord: np.ndarray, depth: int | None = ...
    ) -> OcTreeKey: ...
    def coordToKeyChecked(
        self, coord: np.ndarray, depth: int | None = ...
    ) -> tuple[bool, OcTreeKey | None]: ...
    def deleteNode(self, value: np.ndarray, depth: int = ...) -> bool: ...
    def castRay(
        self,
        origin: np.ndarray,
        direction: np.ndarray,
        end: np.ndarray,
        ignoreUnknownCells: bool = ...,
        maxRange: float = ...,
    ) -> bool: ...
    def write(self, filename: str | bytes | None = ...) -> bool | bytes: ...
    def readBinary(self, filename: str | bytes) -> bool: ...
    def writeBinary(
        self, filename: str | bytes | None = ...
    ) -> bool | bytes: ...
    def isNodeOccupied(self, node: OcTreeNode | iterator_base) -> bool: ...
    def isNodeAtThreshold(self, node: OcTreeNode | iterator_base) -> bool: ...
    def getLabels(self, points: np.ndarray) -> np.ndarray: ...
    def extractPointCloud(self) -> tuple[np.ndarray, np.ndarray]: ...
    def insertPointCloud(
        self,
        pointcloud: np.ndarray,
        origin: np.ndarray,
        maxrange: float = ...,
        lazy_eval: bool = ...,
        discretize: bool = ...,
    ) -> None: ...
    def begin_tree(self, maxDepth: int = ...) -> tree_iterator: ...
    def begin_leafs(self, maxDepth: int = ...) -> leaf_iterator: ...
    def begin_leafs_bbx(
        self, bbx_min: np.ndarray, bbx_max: np.ndarray, maxDepth: int = ...
    ) -> leaf_bbx_iterator: ...
    def end_tree(self) -> tree_iterator: ...
    def end_leafs(self) -> leaf_iterator: ...
    def end_leafs_bbx(self) -> leaf_bbx_iterator: ...
    def getBBXBounds(self) -> np.ndarray: ...
    def getBBXCenter(self) -> np.ndarray: ...
    def getBBXMax(self) -> np.ndarray: ...
    def getBBXMin(self) -> np.ndarray: ...
    def getRoot(self) -> OcTreeNode: ...
    def getNumLeafNodes(self) -> int: ...
    def getResolution(self) -> float: ...
    def getTreeDepth(self) -> int: ...
    def getTreeType(self) -> bytes: ...
    def inBBX(self, p: np.ndarray) -> bool: ...
    def keyToCoord(
        self, key: OcTreeKey, depth: int | None = ...
    ) -> np.ndarray: ...
    def memoryFullGrid(self) -> int: ...
    def memoryUsage(self) -> int: ...
    def memoryUsageNode(self) -> int: ...
    def resetChangeDetection(self) -> None: ...
    def search(
        self, value: OcTreeKey | np.ndarray, depth: int = ...
    ) -> OcTreeNode: ...
    def setBBXMax(self, max: np.ndarray) -> None: ...
    def setBBXMin(self, min: np.ndarray) -> None: ...
    def setResolution(self, r: float) -> None: ...
    def size(self) -> int: ...
    def toMaxLikelihood(self) -> None: ...
    def updateNodes(
        self,
        values: Sequence[OcTreeKey | np.ndarray],
        update: bool | float,
        lazy_eval: bool = ...,
    ) -> None: ...
    def updateNode(
        self,
        value: OcTreeKey | np.ndarray,
        update: bool | float,
        lazy_eval: bool = ...,
    ) -> OcTreeNode: ...
    def updateInnerOccupancy(self) -> None: ...
    def useBBXLimit(self, enable: bool) -> None: ...
    def volume(self) -> float: ...
    def getClampingThresMax(self) -> float: ...
    def getClampingThresMaxLog(self) -> float: ...
    def getClampingThresMin(self) -> float: ...
    def getClampingThresMinLog(self) -> float: ...
    def getOccupancyThres(self) -> float: ...
    def getOccupancyThresLog(self) -> float: ...
    def getProbHit(self) -> float: ...
    def getProbHitLog(self) -> float: ...
    def getProbMiss(self) -> float: ...
    def getProbMissLog(self) -> float: ...
    def setClampingThresMax(self, thresProb: float) -> None: ...
    def setClampingThresMin(self, thresProb: float) -> None: ...
    def setOccupancyThres(self, prob: float) -> None: ...
    def setProbHit(self, prob: float) -> None: ...
    def setProbMiss(self, prob: float) -> None: ...
    def getMetricSize(self) -> np.ndarray: ...
    def getMetricMin(self) -> np.ndarray: ...
    def getMetricMax(self) -> np.ndarray: ...
    def expandNode(self, node: OcTreeNode) -> None: ...
    def createNodeChild(self, node: OcTreeNode, idx: int) -> OcTreeNode: ...
    def getNodeChild(self, node: OcTreeNode, idx: int) -> OcTreeNode: ...
    def isNodeCollapsible(self, node: OcTreeNode) -> bool: ...
    def deleteNodeChild(self, node: OcTreeNode, idx: int) -> None: ...
    def pruneNode(self, node: OcTreeNode) -> bool: ...
    def dynamicEDT_generate(
        self,
        maxdist: float,
        bbx_min: np.ndarray,
        bbx_max: np.ndarray,
        treatUnknownAsOccupied: bool = ...,
    ) -> None: ...
    def dynamicEDT_checkConsistency(self) -> bool: ...
    def dynamicEDT_update(self, updateRealDist: bool) -> None: ...
    def dynamicEDT_getMaxDist(self) -> float: ...
    def dynamicEDT_getDistance(self, p: OcTreeKey | np.ndarray) -> float: ...
    def dynamicEDT_getDistanceAndClosestObstacle(
        self, p: np.ndarray
    ) -> tuple[float, np.ndarray | None]: ...
