import os
from collections.abc import Iterator
from collections.abc import Sequence
from typing import Any
from typing import overload

from numpy.typing import NDArray
from typing_extensions import override

StrOrBytesPath = str | bytes | os.PathLike[str] | os.PathLike[bytes]

class NullPointerException(Exception): ...

class OcTreeKey:
    def __init__(self) -> None: ...
    def __setitem__(self, key: int, value: int) -> None: ...
    def __getitem__(self, key: int) -> int: ...
    @override
    def __eq__(self, other: object) -> bool: ...
    __hash__: None

class OcTreeNode:
    def addValue(self, p: float) -> None: ...
    def childExists(self, i: int) -> bool: ...
    def getValue(self) -> float: ...
    def setValue(self, v: float) -> None: ...
    def getOccupancy(self) -> float: ...
    def getLogOdds(self) -> float: ...
    def setLogOdds(self, l: float) -> None: ...
    def hasChildren(self) -> bool: ...

class ColorOcTreeNode(OcTreeNode):
    def getColor(self) -> tuple[int, int, int]: ...
    def setColor(self, r: int, g: int, b: int) -> None: ...
    def isColorSet(self) -> bool: ...
    def getAverageChildColor(self) -> tuple[int, int, int]: ...

class iterator_base:
    def getCoordinate(self) -> NDArray[Any]: ...
    def getDepth(self) -> int: ...
    def getKey(self) -> OcTreeKey: ...
    def getIndexKey(self) -> OcTreeKey: ...
    def getSize(self) -> float: ...
    def getX(self) -> float: ...
    def getY(self) -> float: ...
    def getZ(self) -> float: ...
    def getOccupancy(self) -> float: ...
    def getValue(self) -> float: ...
    def getColor(self) -> tuple[int, int, int]: ...

class tree_iterator(iterator_base):
    def next(self) -> tree_iterator: ...
    def __iter__(self) -> Iterator[tree_iterator]: ...
    def isLeaf(self) -> bool: ...

class leaf_iterator(iterator_base):
    def next(self) -> leaf_iterator: ...
    def __iter__(self) -> Iterator[leaf_iterator]: ...

class leaf_bbx_iterator(iterator_base):
    def next(self) -> leaf_bbx_iterator: ...
    def __iter__(self) -> Iterator[leaf_bbx_iterator]: ...

class OccupancyOcTreeBase:
    def clear(self) -> None: ...
    @overload
    def write(self) -> bytes: ...
    @overload
    def write(self, filename: StrOrBytesPath) -> bool: ...
    def readBinary(self, filename: StrOrBytesPath) -> bool: ...
    @overload
    def writeBinary(self) -> bytes: ...
    @overload
    def writeBinary(self, filename: StrOrBytesPath) -> bool: ...
    def isNodeOccupied(self, node: OcTreeNode | iterator_base) -> bool: ...
    def isNodeAtThreshold(self, node: OcTreeNode | iterator_base) -> bool: ...
    def getResolution(self) -> float: ...
    def getTreeType(self) -> bytes: ...
    def memoryUsage(self) -> int: ...
    def memoryUsageNode(self) -> int: ...
    def setResolution(self, r: float) -> None: ...
    def size(self) -> int: ...
    def toMaxLikelihood(self) -> None: ...
    def updateNodes(
        self,
        values: Sequence[OcTreeKey | NDArray[Any]],
        update: bool | float,
        lazy_eval: bool = ...,
    ) -> None: ...
    def updateNode(
        self,
        value: OcTreeKey | NDArray[Any],
        update: bool | float,
        lazy_eval: bool = ...,
    ) -> OcTreeNode: ...
    def getClampingThresMax(self) -> float: ...
    def getClampingThresMaxLog(self) -> float: ...
    def getClampingThresMin(self) -> float: ...
    def getClampingThresMinLog(self) -> float: ...
    def getOccupancyThres(self) -> float: ...
    def getOccupancyThresLog(self) -> float: ...
    def getProbHit(self) -> float: ...
    def getProbHitLog(self) -> float: ...
    def getProbMiss(self) -> float: ...
    def getProbMissLog(self) -> float: ...
    def setClampingThresMax(self, thresProb: float) -> None: ...
    def setClampingThresMin(self, thresProb: float) -> None: ...
    def setOccupancyThres(self, prob: float) -> None: ...
    def setProbHit(self, prob: float) -> None: ...
    def setProbMiss(self, prob: float) -> None: ...
    def getMetricSize(self) -> NDArray[Any]: ...
    def getMetricMin(self) -> NDArray[Any]: ...
    def getMetricMax(self) -> NDArray[Any]: ...

class OcTree(OccupancyOcTreeBase):
    def __init__(self, arg: float | StrOrBytesPath) -> None: ...
    @staticmethod
    def read(filename: StrOrBytesPath) -> OcTree: ...
    def adjustKeyAtDepth(self, key: OcTreeKey, depth: int) -> OcTreeKey: ...
    def bbxSet(self) -> bool: ...
    def calcNumNodes(self) -> int: ...
    def coordToKey(
        self, coord: NDArray[Any], depth: int | None = ...
    ) -> OcTreeKey: ...
    def coordToKeyChecked(
        self, coord: NDArray[Any], depth: int | None = ...
    ) -> tuple[bool, OcTreeKey | None]: ...
    def deleteNode(self, value: NDArray[Any], depth: int = ...) -> bool: ...
    def castRay(
        self,
        origin: NDArray[Any],
        direction: NDArray[Any],
        end: NDArray[Any],
        ignoreUnknownCells: bool = ...,
        maxRange: float = ...,
    ) -> bool: ...
    def getLabels(self, points: NDArray[Any]) -> NDArray[Any]: ...
    def extractPointCloud(self) -> tuple[NDArray[Any], NDArray[Any]]: ...
    def insertPointCloud(
        self,
        pointcloud: NDArray[Any],
        origin: NDArray[Any],
        maxrange: float = ...,
        lazy_eval: bool = ...,
        discretize: bool = ...,
    ) -> None: ...
    def begin_tree(self, maxDepth: int = ...) -> tree_iterator: ...
    def begin_leafs(self, maxDepth: int = ...) -> leaf_iterator: ...
    def begin_leafs_bbx(
        self, bbx_min: NDArray[Any], bbx_max: NDArray[Any], maxDepth: int = ...
    ) -> leaf_bbx_iterator: ...
    def end_tree(self) -> tree_iterator: ...
    def end_leafs(self) -> leaf_iterator: ...
    def end_leafs_bbx(self) -> leaf_bbx_iterator: ...
    def getBBXBounds(self) -> NDArray[Any]: ...
    def getBBXCenter(self) -> NDArray[Any]: ...
    def getBBXMax(self) -> NDArray[Any]: ...
    def getBBXMin(self) -> NDArray[Any]: ...
    def getRoot(self) -> OcTreeNode: ...
    def getNumLeafNodes(self) -> int: ...
    def getTreeDepth(self) -> int: ...
    def inBBX(self, p: NDArray[Any]) -> bool: ...
    def keyToCoord(
        self, key: OcTreeKey, depth: int | None = ...
    ) -> NDArray[Any]: ...
    def memoryFullGrid(self) -> int: ...
    def resetChangeDetection(self) -> None: ...
    def search(
        self, value: OcTreeKey | NDArray[Any], depth: int = ...
    ) -> OcTreeNode: ...
    def setBBXMax(self, max: NDArray[Any]) -> None: ...
    def setBBXMin(self, min: NDArray[Any]) -> None: ...
    def updateInnerOccupancy(self) -> None: ...
    def useBBXLimit(self, enable: bool) -> None: ...
    def volume(self) -> float: ...
    def expandNode(self, node: OcTreeNode) -> None: ...
    def createNodeChild(self, node: OcTreeNode, idx: int) -> OcTreeNode: ...
    def getNodeChild(self, node: OcTreeNode, idx: int) -> OcTreeNode: ...
    def isNodeCollapsible(self, node: OcTreeNode) -> bool: ...
    def deleteNodeChild(self, node: OcTreeNode, idx: int) -> None: ...
    def pruneNode(self, node: OcTreeNode) -> bool: ...
    def dynamicEDT_generate(
        self,
        maxdist: float,
        bbx_min: NDArray[Any],
        bbx_max: NDArray[Any],
        treatUnknownAsOccupied: bool = ...,
    ) -> None: ...
    def dynamicEDT_checkConsistency(self) -> bool: ...
    def dynamicEDT_update(self, updateRealDist: bool) -> None: ...
    def dynamicEDT_getMaxDist(self) -> float: ...
    def dynamicEDT_getDistance(self, p: OcTreeKey | NDArray[Any]) -> float: ...
    def dynamicEDT_getDistanceAndClosestObstacle(
        self, p: NDArray[Any]
    ) -> tuple[float, NDArray[Any] | None]: ...

class ColorOcTree(OccupancyOcTreeBase):
    def __init__(self, resolution: float) -> None: ...
    @staticmethod
    def read(filename: StrOrBytesPath) -> ColorOcTree: ...
    def setNodeColor(
        self, value: OcTreeKey | NDArray[Any], r: int, g: int, b: int
    ) -> ColorOcTreeNode: ...
    def averageNodeColor(
        self, value: OcTreeKey | NDArray[Any], r: int, g: int, b: int
    ) -> ColorOcTreeNode: ...
    def integrateNodeColor(
        self, value: OcTreeKey | NDArray[Any], r: int, g: int, b: int
    ) -> ColorOcTreeNode: ...
    @override
    def updateNode(
        self,
        value: OcTreeKey | NDArray[Any],
        update: bool | float,
        lazy_eval: bool = ...,
    ) -> ColorOcTreeNode: ...
    def adjustKeyAtDepth(self, key: OcTreeKey, depth: int) -> OcTreeKey: ...
    def bbxSet(self) -> bool: ...
    def calcNumNodes(self) -> int: ...
    def coordToKey(
        self, coord: NDArray[Any], depth: int | None = ...
    ) -> OcTreeKey: ...
    def coordToKeyChecked(
        self, coord: NDArray[Any], depth: int | None = ...
    ) -> tuple[bool, OcTreeKey | None]: ...
    def deleteNode(self, value: NDArray[Any], depth: int = ...) -> bool: ...
    def castRay(
        self,
        origin: NDArray[Any],
        direction: NDArray[Any],
        end: NDArray[Any],
        ignoreUnknownCells: bool = ...,
        maxRange: float = ...,
    ) -> bool: ...
    def insertPointCloud(
        self,
        pointcloud: NDArray[Any],
        origin: NDArray[Any],
        maxrange: float = ...,
        lazy_eval: bool = ...,
        discretize: bool = ...,
    ) -> None: ...
    def begin_tree(self, maxDepth: int = ...) -> tree_iterator: ...
    def begin_leafs(self, maxDepth: int = ...) -> leaf_iterator: ...
    def begin_leafs_bbx(
        self, bbx_min: NDArray[Any], bbx_max: NDArray[Any], maxDepth: int = ...
    ) -> leaf_bbx_iterator: ...
    def end_tree(self) -> tree_iterator: ...
    def end_leafs(self) -> leaf_iterator: ...
    def end_leafs_bbx(self) -> leaf_bbx_iterator: ...
    def getBBXBounds(self) -> NDArray[Any]: ...
    def getBBXCenter(self) -> NDArray[Any]: ...
    def getBBXMax(self) -> NDArray[Any]: ...
    def getBBXMin(self) -> NDArray[Any]: ...
    def getRoot(self) -> ColorOcTreeNode: ...
    def getNumLeafNodes(self) -> int: ...
    def getTreeDepth(self) -> int: ...
    def inBBX(self, p: NDArray[Any]) -> bool: ...
    def keyToCoord(
        self, key: OcTreeKey, depth: int | None = ...
    ) -> NDArray[Any]: ...
    def memoryFullGrid(self) -> int: ...
    def resetChangeDetection(self) -> None: ...
    def search(
        self, value: OcTreeKey | NDArray[Any], depth: int = ...
    ) -> ColorOcTreeNode: ...
    def setBBXMax(self, max: NDArray[Any]) -> None: ...
    def setBBXMin(self, min: NDArray[Any]) -> None: ...
    def updateInnerOccupancy(self) -> None: ...
    def useBBXLimit(self, enable: bool) -> None: ...
    def volume(self) -> float: ...
    def expandNode(self, node: ColorOcTreeNode) -> None: ...
    def createNodeChild(
        self, node: ColorOcTreeNode, idx: int
    ) -> ColorOcTreeNode: ...
    def getNodeChild(
        self, node: ColorOcTreeNode, idx: int
    ) -> ColorOcTreeNode: ...
    def isNodeCollapsible(self, node: ColorOcTreeNode) -> bool: ...
    def deleteNodeChild(self, node: ColorOcTreeNode, idx: int) -> None: ...
    def pruneNode(self, node: ColorOcTreeNode) -> bool: ...
